const $ = (id) => document.getElementById(id);
const form = $("form-gasto"), lista = $("lista-gastos"), vazia = $("mensagem-vazia"), dataInput = $("data");
const nomesMetodo = { pix: "Pix", credito: "Crédito", debito: "Débito" };
let gastos = [], editandoId = null;
const hoje = () => new Date().toLocaleDateString("en-CA");
dataInput.value = hoje();
function moeda(v) { return Number(v).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
function dataBR(v) { return new Date(`${v}T12:00:00`).toLocaleDateString("pt-BR"); }
function mostrarToast(msg, erro = false) { const t = $("toast"); t.textContent = msg; t.className = `toast show ${erro ? "error" : ""}`; setTimeout(() => t.className = "toast", 2800); }
function filtrosAplicados(g) { const busca = $("filtro-busca").value.toLowerCase(); const metodo = $("filtro-metodo").value; const periodo = $("filtro-periodo").value; const agora = new Date(); const d = new Date(`${g.data}T12:00:00`); if (busca && !`${g.descricao} ${g.categoria}`.toLowerCase().includes(busca)) return false; if (metodo && g.metodo !== metodo) return false; if (periodo === "mes" && (d.getMonth() !== agora.getMonth() || d.getFullYear() !== agora.getFullYear())) return false; if (periodo === "7dias" && (agora - d) > 7 * 86400000) return false; return true; }
function renderizar() { const visiveis = gastos.filter(filtrosAplicados); lista.innerHTML = ""; vazia.style.display = visiveis.length ? "none" : "block"; $("contador").textContent = `${visiveis.length} ${visiveis.length === 1 ? "lançamento" : "lançamentos"}`; visiveis.forEach(g => { const li = document.createElement("li"); li.className = `item-gasto ${g.metodo}`; li.innerHTML = `<div class="item-info"><strong>${g.descricao}</strong><span>${g.categoria || "Outros"} · ${nomesMetodo[g.metodo]} · ${dataBR(g.data)}</span></div><div class="item-direita"><strong>${moeda(g.valor)}</strong><div class="acoes"><button class="btn-editar" data-id="${g.id}" title="Editar">✎</button><button class="btn-excluir" data-id="${g.id}" title="Excluir">×</button></div></div>`; lista.appendChild(li); }); document.querySelectorAll(".btn-excluir").forEach(b => b.onclick = () => excluirGasto(b.dataset.id)); document.querySelectorAll(".btn-editar").forEach(b => b.onclick = () => iniciarEdicao(b.dataset.id)); }
async function atualizarResumo() { const r = await fetch("/api/resumo"); if (!r.ok) throw Error(); const x = await r.json(); $("total-geral").textContent = moeda(x.total); $("total-pix").textContent = moeda(x.por_metodo.pix); $("total-credito").textContent = moeda(x.por_metodo.credito); $("total-debito").textContent = moeda(x.por_metodo.debito); }
async function atualizar() { const r = await fetch("/api/gastos"); if (!r.ok) throw Error(); gastos = await r.json(); renderizar(); await atualizarResumo(); }
function limparForm() { form.reset(); dataInput.value = hoje(); document.querySelector('input[value="pix"]').checked = true; editandoId = null; $("form-titulo").textContent = "Adicionar gasto"; $("btn-submit").textContent = "Adicionar gasto"; $("btn-cancelar").classList.add("hidden"); }
function iniciarEdicao(id) { const g = gastos.find(x => String(x.id) === String(id)); if (!g) return; editandoId = g.id; $("descricao").value = g.descricao; $("valor").value = g.valor; $("categoria").value = g.categoria; dataInput.value = g.data; document.querySelector(`input[value="${g.metodo}"]`).checked = true; $("form-titulo").textContent = "Editar gasto"; $("btn-submit").textContent = "Salvar alterações"; $("btn-cancelar").classList.remove("hidden"); window.scrollTo({ top: 0, behavior: "smooth" }); }
async function excluirGasto(id) { const g = gastos.find(x => String(x.id) === String(id)); if (!confirm(`Excluir “${g?.descricao || "este gasto"}”?`)) return; const r = await fetch(`/api/gastos/${id}`, { method: "DELETE" }); if (!r.ok) return mostrarToast("Não foi possível excluir o gasto.", true); mostrarToast("Gasto excluído."); await atualizar(); }
form.onsubmit = async e => { e.preventDefault(); const dados = { descricao: $("descricao").value, valor: $("valor").value, categoria: $("categoria").value, data: dataInput.value, metodo: document.querySelector('input[name="metodo"]:checked').value }; const url = editandoId ? `/api/gastos/${editandoId}` : "/api/gastos"; const r = await fetch(url, { method: editandoId ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(dados) }); if (!r.ok) { const erro = await r.json().catch(() => ({})); return mostrarToast(erro.erro || "Confira os dados informados.", true); } mostrarToast(editandoId ? "Gasto atualizado." : "Gasto adicionado."); limparForm(); await atualizar(); };
$("btn-cancelar").onclick = limparForm; ["filtro-busca", "filtro-metodo", "filtro-periodo"].forEach(id => $(id).oninput = renderizar); atualizar().catch(() => mostrarToast("Não foi possível carregar os gastos.", true));
